" -----------------------------------------------------------------------------
" Vim editor config values
" -----------------------------------------------------------------------------

set number
set showcmd
set foldmethod=marker

" Needed for Syntax Highlighting
filetype on
syntax on
filetype plugin on
set grepprg=grep\ -nH\ $*

" Who doesn't like autoindent?
set autoindent

" Highlight current line
set cursorline

" Use spaces for tabulatio:n <3
set expandtab
set smarttab

" Who wants an 8 character tab?
set shiftwidth=4
set tabstop=4
set softtabstop=4

" Disable swap files
set noswapfile

" Highlight the search
set hlsearch

" Disable the terminal bell
set visualbell t_vb=

" Color theme, available themes:
colorscheme afterglow

" Pathogen: Plugin autoloading runtime
execute pathogen#infect()
call pathogen#helptags()

" -----------------------------------------------------------------------------
" MacVim / graphical vim configuration
" -----------------------------------------------------------------------------

" set guifont=Monaco:h12

" Graphical vim will work with no dialogs.
set guioptions=c

" -----------------------------------------------------------------------------
" Plugin configuration
" -----------------------------------------------------------------------------

" --------------------
" NERDTree      
" --------------------

let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

" Quit vim if NERDTree is the last buffer
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" --------------------
" Markdown Preview      
" --------------------
let g:instant_markdown_autostart = 0

" --------------------
" Syntastic (used by eclim)
" --------------------
" let g:syntastic_php_checkers = ['php', 'phpcs']
" let g:syntastic_php_php_exec = '/opt/local/bin/php'

" --------------------
" Airline      
" --------------------

" Airline buffers tab
let g:airline#extensions#tabline#enabled = 1

" Just show the filename (no path) in the tab
let g:airline#extensions#tabline#fnamemod = ':t'

" --------------------
" Vim Wiki
" --------------------

" Vim Wiki configuration
let g:vimwiki_list = [{'path': '~/.vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]

" Disable TAB for Vim Wiki
let g:vimwiki_table_mappings = 0

" -----------------------------------------------------------------------------
" Key maps
" -----------------------------------------------------------------------------

" allow the . to execute once for each line of a visual selection
" vnoremap . :normal .<CR>

" Toggle NRDTree with CTRL+N
map <C-n> :NERDTreeToggle<CR>

" Markdown preview
map <leader>mp :set ft=markdown \| e \| InstantMarkdownPreview<CR>

" Format JSON
map <leader>jsf :% !python -m json.tool<CR>

" Close buffer from nerdtree without exit vim
nnoremap <S-w> :bp\|bd #<CR>

" Expand Emmet with tab in insert mode (this shit is annoying)
" imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")

" Remove hlsearch with double CTRL+C
nnoremap <C-c><C-c> :silent! nohls<cr>

" Opent the current file's directory in NERDTree with \r
map <leader>r :NERDTreeFind<cr>

" VimWiki, disable fucking backspace
nmap <Leader>wb <Plug>VimwikiGoBackLink

" Navigation between buffers with SHIFT+h and SHIFT+l
map <S-h> :bprev!<CR>
map <S-l> :bnext!<CR>

" Enable paste on gvim (Linux)
nmap <C-V> "+gP
imap <C-V> <ESC><C-V>i
vmap <C-C> "+y 

